services:
  postgres:
    container_name: postgres
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
